# Opciones de financiamiento para el proyecto
# Descomenta las líneas que apliquen

# github: [tu-usuario]
# patreon: tu-patreon
# open_collective: bc-rust
# ko_fi: tu-kofi
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: tu-usuario
# issuehunt: tu-usuario
# otechie: tu-usuario
# lfx_crowdfunding: project-name
# custom: ['https://tu-link-de-donacion.com']
